version: '3.8'

services:
  app:
    build: .
    container_name: recipe-app
    volumes:
      - .:/app
    command: python recipes.py

  tests:
    build: .
    container_name: recipe-tests
    volumes:
      - .:/app
    command: pytest test_recipes.py